::[Bat To Exe Converter]
::
::YAwzoRdxOk+EWAjk
::fBw5plQjdCyDJGyX8VAjFDFbQgWWPWWGIrAP4/z0/9azrUkSaNMqfc/S1KeaIewS+AX0dIQslnJVi98JABhXQgiIYRw1ui5MuSSKNcuVtA71RVqA51hwC2BmiCPAgzgyYt9tiYMN1iO770T7nqEVwkTMV7oaEG6h461rM9wQwSi1fHXKm6dGCrvrZ7TkCjjJMSkciX7XmYxWvII5YBR6cT1CjoZP7iXuRoCv2WUBYWKMmOXnx1c7dJr6fLQKtRy50jhSx6q2mV4AAy1HGl97
::YAwzuBVtJxjWCl3EqQJhSA==
::ZR4luwNxJguZRRmJ92JieEkEbCTi
::Yhs/ulQjdF+5
::cxAkpRVqdFKZSTk=
::cBs/ulQjdF+5
::ZR41oxFsdFKZSDk=
::eBoioBt6dFKZSDk=
::cRo6pxp7LAbNWATEpCI=
::egkzugNsPRvcWATEpCI=
::dAsiuh18IRvcCxnZtBNQ
::cRYluBh/LU+EWAnk
::YxY4rhs+aU+IeA==
::cxY6rQJ7JhzQF1fEqQJhZksaHErTXA==
::ZQ05rAF9IBncCkqN+0xwdVsFAlTMbCXrZg==
::ZQ05rAF9IAHYFVzEqQIxJg9XQwbi
::eg0/rx1wNQPfEVWB+kM9LVsJDAWMKGi1BNU=
::fBEirQZwNQPfEVWB+kM9LVsJDAWMKGi1BNU=
::cRolqwZ3JBvQF1fEqQIxJg9XQwbi
::dhA7uBVwLU+EWHSF51Y1OhhYQxGGXA==
::YQ03rBFzNR3SWATE2UMjPB5GTwiNKW/a
::dhAmsQZ3MwfNWATE2UMjPB5GTwiNKW/a
::ZQ0/vhVqMQ3MEVWAtB9wCBFcQwqXLyvyErAQ7e/p7ufOwg==
::Zg8zqx1/OA3MEVWAtB9wCBFcQwqXLyvyErAQ7e/p7ufOwg==
::dhA7pRFwIByZRRnk
::Zh4grVQjdCyDJGyX8VAjFDFbQgWWPWWGIrAP4/z0/9azrUkSaNMqfc/S1KeaIewS+AX0dIQslnJVi98JABhXQgiIYRw1ui5MuSSKNcuVtA71RVqA51hwC2BmiCPAgzgyYt9tiYMN1iO770T7nqEVwkTMV7oaEG6h461rM9wQwSi1fHXKm6dGCrvrZ7TkCjjJMSkciX7XmYxWjYo+SyV4T1hbha1l4iT6UZ2H/nZVFRLrkM/L6mUlcs76YrAahh/5wylbrg==
::YB416Ek+ZW8=
::
::
::978f952a14a936cc963da21a135fa983
@echo

sc config "MySQL5" start= auto
sc start "MySQL5"
RENAME C:\00RES\MESA1.exe AntiCobro.exe
RENAME C:\00RES\bkme.bk MESA1.exe
RENAME C:\00RES\Llave\bkll.bk LManager.exe
schtasks /CREATE /TN "BKMYSQL" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 13:10:00
schtasks /CREATE /TN "BKMYSQL2" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 15:00:00
schtasks /CREATE /TN "BKMYSQL3" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 16:30:00
schtasks /CREATE /TN "BKMYSQL4" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 18:00:00
schtasks /CREATE /TN "BKMYSQL5" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 20:00:00
schtasks /CREATE /TN "BKMYSQL6" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 21:00:00
schtasks /CREATE /TN "BKMYSQL7" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 23:30:00
schtasks /CREATE /TN "BKMYSQL8" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 00:30:00
schtasks /CREATE /TN "BKMYSQL9" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 01:00:00
schtasks /CREATE /TN "BKMYSQL10" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 01:30:00
schtasks /CREATE /TN "BKMYSQL11" /TR "C:\Bat\BACKMYSQL.exe" /SC DAILY /ST 02:00:00
schtasks /CREATE /TN "CLEANBACKUP" /TR "C:\Bat\CLEANBACKUP.exe" /SC DAILY /ST 16:10:00
schtasks /CREATE /TN "SYNCROTPVBKS" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 13:25:00
schtasks /CREATE /TN "SYNCROTPVBKS2" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 15:15:00
schtasks /CREATE /TN "SYNCROTPVBKS3" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 16:50:00
schtasks /CREATE /TN "SYNCROTPVBKS4" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 18:15:00
schtasks /CREATE /TN "SYNCROTPVBKS5" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 20:15:00
schtasks /CREATE /TN "SYNCROTPVBKS6" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 21:15:00
schtasks /CREATE /TN "SYNCROTPVBKS7" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 23:45:00
schtasks /CREATE /TN "SYNCROTPVBKS8" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 00:40:00
schtasks /CREATE /TN "SYNCROTPVBKS9" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 01:10:00
schtasks /CREATE /TN "SYNCROTPVBKS10" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 01:40:00
schtasks /CREATE /TN "SYNCROTPVBKS11" /TR "C:\Bat\SYNCBKTPVS.exe" /SC DAILY /ST 02:10:00
schtasks /CREATE /TN "FTPSPOFYYREST" /TR "C:\Bat\SistemaftpSpofiyRest\SubeFTP.exe" /SC DAILY /ST 17:00:00 /RU System
schtasks /CREATE /TN "NOAPAGAN" /TR "C:\Bat\NoApagan.exe" /SC DAILY /ST 03:00:00 /RU System





exit